apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider-financial-instrument-valuation-models
  namespace: tesopro
spec:
  provider: aws
  secretObjects:
    - secretName: secrets-dev-bcl-financial-instrument-valuation-models
      type: Opaque
      data:
        - objectName: accesskeyid
          key: bcl-clientid
        - objectName: secretaccesskey
          key: bcl-apikey
  parameters:
    objects: |
      - objectName: "APIKey/dev/inner/bcl/tesoreria"
        objectType: secretsmanager
        jmesPath:
          - path: clientid
            objectAlias: accesskeyid
          - path: clientsecret
            objectAlias: secretaccesskey    
